### ISSUE TITLE
Depth Pixelwise

### ISSUE THREAD

**Issue by marcomiglionico94** [CYang0515/NonCuboidRoom#11]
I was reviewing the code, i noticed that dt_params3d_pixelwise is not used in the code. Line 326 in `test.py`

`# post process on output feature map size, and extract planes, lines, plane params instance and plane params pixelwise
        dt_planes, dt_lines, dt_params3d_instance, dt_params3d_pixelwise = post_process(x, Mnms=1)`

In the function ConvertLayout  in `reconstruction.py` there is a parameter called pixelwise which is set to None. If i try to assign `dt_params3d_pixelwise` to the pixelwise parameter function of Convert Layout i get an error. 

`# opt results
            seg, depth, img, polys = ConvertLayout(
                inputs['img'][i], ups, downs, attribution, K=inputs['intri'][i].cpu().numpy(),
                pwalls=params_layout, pfloor=pfloor, pceiling=pceiling,
                ixy1map=inputs['ixy1map'][i].cpu().numpy(),
                valid=inputs['iseg'][i].cpu().numpy(),
                oxy1map=inputs['oxy1map'][i].cpu().numpy(),
                pixelwise=None
            )`

So my questions are:

- What is dt_params3d_pixelwise used for?
- What should be passed to the function ConvertLayout as pixelwise parameters, when is not set to None.

Thanks

**Comment by CYang0515** [comment]
The `dt_params3d_pixelwise` is the predicted plane 3d parameter map (normal and offset), and we only use the value (`dt_params3d_instance`) located on the plane center. 
The `dt_params3d_pixelwise` of  ConvertLayout `function` is to get pixel-wise depth directly by the predicted plane 3d parameter, you can set it to dt_params3d_pixelwise[i]. But our method does not use it.
