### ISSUE TITLE
Future Improvements Ideas

### ISSUE THREAD

**Issue by marcomiglionico94** [CYang0515/NonCuboidRoom#12]
Hello guys, I really appreciate the work and I was finally able to reconstruct and visualize my room from a 2d picture.

<img width="641" alt="Screen Shot 2021-12-06 at 5 05 12 PM" src="https://user-images.githubusercontent.com/19528605/144880155-b50cdc9c-3afa-49f5-95ca-b0885edd40bd.png">

I was wandering if you have any directions/ideas on how we could combine different predictions from different images of the same room, to obtain a complete layout reconstruction of the full room. The idea would be to we take 3 or 4 partially overlapping pictures that cover the whole room and then having a full 3D reconstruction of the room, maybe by using the camera intrinsics and extrinsics and the by joining the extracted planes. This is just an idea but I wanted to know if you thought about it and if you think is something feasible or not. Thanks a lot.

**Comment by bertjiazheng** [comment]
Hi @marcomiglionico94 

If you already have all intrinsic and extrinsic information, you can fuse each single-view reconstructed model into a complete model. If not, I am not sure the relative pose estimation could work well if the two views do not have enough overlapped area.

I list several relevant works here and hope it helps. 

- [Planar Surface Reconstruction From Sparse Views](https://jinlinyi.github.io/SparsePlanes/)
- [Floorplan-Jigsaw: Jointly Estimating Scene Layout and Aligning Partial Scans](https://enigma-li.github.io/projects/indoorRecons/floorplanJigsaw.html)

Best,
Jia

**Comment by ebrahimkhalilabbasi** [comment]
Hello @marcomiglionico94 
Could you please share your code of visualisation?
