### ISSUE TITLE
Can I generate 3D models from code

### ISSUE THREAD

**Issue by HongLouyemeng** [CYang0515/NonCuboidRoom#13]
Thanks for your excellent work！

**Comment by ebrahimkhalilabbasi** [comment]
Hi @HongLouyemeng
Have you made any progress to generate 3D models from this code?

**Comment by HongLouyemeng** [comment]
> Hi @HongLouyemeng Have you made any progress to generate 3D models from this code?

No, I turned to research in robotics OVO
