### ISSUE TITLE
question regarding the network design choice

### ISSUE THREAD

**Issue by Cli98** [CYang0515/NonCuboidRoom#16]
Hi author,

I have a question regarding the network design.

From the planar detection (Section 3.1), you indicated that "Each channel of the center likelihood map C represents different categories"., and looks like that you attempt to solve planar detection + classification of wall/ceiling/floor together via center likelihood map.

This make me confused. As the channel for offset is still H*W*2 instead of H*W*6, where it looks like that wall/ceiling/floor share the same offset. I am not quite understand the design here as normally, the offset for wall/ceiling/floor may not be the same. Could you make some comments for my question? and will it make more sense to decouple them to keypoint detection + classification instead?

Thank you if you can consider answer my question.

**Comment by bertjiazheng** [comment]
Hi, 

Thanks for your interest in our work! This architecture design is the same as [CenterNet](https://github.com/xingyizhou/CenterNet): 

> All classes _c_ share the same offset prediction.

Best,
Jia

**Comment by Cli98** [comment]
> Hi,
> 
> Thanks for your interest in our work! This architecture design is the same as [CenterNet](https://github.com/xingyizhou/CenterNet):
> 
> > All classes _c_ share the same offset prediction.
> 
> Best, Jia

Thank you for answering my question.
