### ISSUE TITLE
Something wrong with testing Structured3D dataset

### ISSUE THREAD

**Issue by zhangjingxian1998** [CYang0515/NonCuboidRoom#17]
I downloaded Structured3D dataset and 2D line annotations which contains 6280 labels, but I found that scene_03499_142535_2 is not exist in my downloaded dataset. 
And I found some totally wrong label like this (the second col is GT)
scene_03253_533743_4
![1710_select](https://user-images.githubusercontent.com/81813465/205539458-4f348b0b-c350-4a1c-9afd-a685ed438e45.png)
scene_03440_527_3
![2755_select](https://user-images.githubusercontent.com/81813465/205539694-c068ac21-c584-4565-b9c3-8ac5304d1333.png)
scene_03394_4372_0
![1256_select](https://user-images.githubusercontent.com/81813465/205539867-29612f66-3c24-4b55-93a8-c55c24a6c1ec.png)

**Comment by bertjiazheng** [comment]
Hi @zhangjingxian1998 ,

Thanks for your interest in our paper. 

We used a pre-released version of the Structured3D dataset in this paper. There may be some differences, but I think this may not be a big issue.

These are some "tricky" cases. The cameras are looking at another room through a door/window, but the layout where the camera is located is shown.

Best,
Jia

**Comment by zhangjingxian1998** [comment]
Thank you!
