### ISSUE TITLE
CUDA out of memory. Tried to allocate 20.00 MiB. GPU 

### ISSUE THREAD

**Issue by HardikJain02** [CYang0515/NonCuboidRoom#20]
When I run this command `python test.py --pretrained ./pretrained/NYU303_pretrained.pt --data NYU303` 
I get this error [output.log](https://github.com/user-attachments/files/15926019/output.log)

My machine: 
![image](https://github.com/CYang0515/NonCuboidRoom/assets/69311953/4c9a5d08-a406-4d63-9877-49e51251d0ef)

**Comment by HardikJain02** [comment]
@bertjiazheng @CYang0515

**Comment by HardikJain02** [comment]
Solved

**Comment by EagleMan11** [comment]
> 解决

how did you solve this problem?
