### ISSUE TITLE
How to calculate the value of metric PE without semantic infomantion?

### ISSUE THREAD

**Issue by Hui-Yao** [CYang0515/NonCuboidRoom#8]
Hello, Thanks for the impressive work of you and your team!

The output of your network are planes, lines and plane parameters, and there is no semantic infomation included in the output , so  i`m very confuse about the computing method of metric PE,  expecting for your reply.

Thanks again.

**Comment by CYang0515** [comment]
We use the detected planes,lines and plane parameters to reconsturct the room layout as discribed in paper. The reconstruction code is [here](https://github.com/CYang0515/NonCuboidRoom/blob/e72a40c1c2530254ae0059731fbdb97e29059d1e/models/reconstruction.py#L701). Then, we use reconstruction results to generate the segmenatation and the code is [here](https://github.com/CYang0515/NonCuboidRoom/blob/e72a40c1c2530254ae0059731fbdb97e29059d1e/models/reconstruction.py#L509).

**Comment by Hui-Yao** [comment]
#planes: a list [[x y x y score cls], ...]             # cls is of [ceiling, floor, wall]

In your hypothesis, there is only one ceiling and one floor in the room model, but several walls exist, and the semantic information output by the plane detection branch can only distinguish three categories: ceiling, floor and wall. Therefore, for each wall, how do you determine the corresponding relationship between the predicted one and the GT one?
thanks for reply!

**Comment by CYang0515** [comment]
There are two ways to determine the corresponding relationship: 1. For each gt plane, match the Max-IOU prediction. The code is [here](https://github.com/CYang0515/NonCuboidRoom/blob/e72a40c1c2530254ae0059731fbdb97e29059d1e/test.py#L85) 2. Use the Hungarian Alg. to match. The code is [here](https://github.com/CYang0515/NonCuboidRoom/blob/e72a40c1c2530254ae0059731fbdb97e29059d1e/test.py#L16)

**Comment by Hui-Yao** [comment]
thanks a lot!



At 2021-11-06 11:21:10, "CYang0515" ***@***.***> wrote:

There are two ways to determine the corresponding relationship: 1. For each gt plane, match the Max-IOU prediction. The code is here 2. Use the Hungarian Alg. to match. The code is here

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
