### ISSUE TITLE
Inference on custom data

### ISSUE THREAD

**Issue by Hui-Yao** [CYang0515/NonCuboidRoom#9]
I am doing some inference using the Structure3D_pretrained.pt model which is downloaded from this repo,  and the custom image is come from the InteriorNet dataset, which is introduced by the KuJiaLe, too.
The image size is (480, 640), and the camera intrinsic is [[600, 0, 320], [0, 600, 240], [0, 0, 1]. 

Part of the result output by the model seems to be reasonable, but other result is hard to accept. 
So should i change the intrinsic matrix ? or how should i modify the hyperparameter setting ?
Any suggestion will be grateful.

In the following pictures, red is the GT edge and green is predicted by the model:
![comparison_1509_1602_3FO4II8OLSP6_Dining_room_6](https://user-images.githubusercontent.com/52377012/143245344-a56ae3c1-36b5-4e9c-919a-9792138c0266.png)
![comparison_1201_1301_3FO4IGB214OC_Dining_room_17](https://user-images.githubusercontent.com/52377012/143245371-03ee80a5-360f-40e0-95cc-6827750b48d7.png)
![comparison_807_909_3FO4IDX9JIBX_Bathroom_2](https://user-images.githubusercontent.com/52377012/143245485-d05e00a9-0d7b-42c2-886e-1e070a1176b7.png)
![comparison_910_1011_3FO4IEQVRLOT_Kids_room_5](https://user-images.githubusercontent.com/52377012/143247231-3b5a8106-fc4a-4c5a-b59c-eb515e215a75.png)
![comparison_2607_2702_3FO4ILIXGI9L_Dining_room_13](https://user-images.githubusercontent.com/52377012/143247262-ac936430-2611-42b6-ab6c-da1b479dea6a.png)

**Comment by marcomiglionico94** [comment]
Which one is the model prediction? The green? If yes what is the red instead?

**Comment by Hui-Yao** [comment]
> Which one is the model prediction? The green? If yes what is the red instead?

The red one is the Ground Truth edge, and the green one is predicted by the model.
